---
title: "DS5001_HW4"
author: "Christopher Langevin"
date: "12/7/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(shiny)

data <- read.csv("C:/Users/chris/ShinyApp/Life_Expectancy_Data.csv")
head(data)
```

```{r}
regression_data <- data %>%
  select(Life.expectancy, Adult.Mortality, Alcohol, BMI, GDP, Schooling, Population)
```

```{r}
model <- lm(Life.expectancy ~ Adult.Mortality + Alcohol + BMI + GDP + Schooling, data = regression_data)
summary(model)

#predict values
regression_data$Predicted_Life_Expectancy <- predict(model, regression_data)

#actual vs predicted
ggplot(regression_data, aes(x = Life.expectancy, y = Predicted_Life_Expectancy)) +
  geom_point() +
  geom_abline(color = "red") +
  labs(title = "Actual vs Predicted Life Expectancy", x = "Actual", y = "Predicted")
```

```{r}

```


```{r}
#UI
ui <- fluidPage(
  titlePanel("Life Expectancy Regression Analysis"),
  sidebarLayout(
    sidebarPanel(
      sliderInput("gdp", "GDP:", 
                  min = min(regression_data$GDP, na.rm = TRUE), 
                  max = max(regression_data$GDP, na.rm = TRUE), 
                  value = median(regression_data$GDP, na.rm = TRUE)),
      sliderInput("schooling", "Schooling:", 
                  min = min(regression_data$Schooling, na.rm = TRUE), 
                  max = max(regression_data$Schooling, na.rm = TRUE), 
                  value = median(regression_data$Schooling, na.rm = TRUE)),
      sliderInput("bmi", "BMI:", 
                  min = min(regression_data$BMI, na.rm = TRUE), 
                  max = max(regression_data$BMI, na.rm = TRUE), 
                  value = median(regression_data$BMI, na.rm = TRUE)),
      sliderInput("adult_mortality", "Adult Mortality:", 
                  min = min(regression_data$Adult.Mortality, na.rm = TRUE), 
                  max = max(regression_data$Adult.Mortality, na.rm = TRUE), 
                  value = median(regression_data$Adult.Mortality, na.rm = TRUE)),
      sliderInput("alcohol", "Alcohol Consumption:", 
                  min = min(regression_data$Alcohol, na.rm = TRUE), 
                  max = max(regression_data$Alcohol, na.rm = TRUE), 
                  value = median(regression_data$Alcohol, na.rm = TRUE))
    ),
    mainPanel(
      textOutput("prediction"),
      plotOutput("regressionPlot")
    )
  )
)

#Server
server <- function(input, output) {
  output$prediction <- renderText({
    new_data <- data.frame(
      Adult.Mortality = input$adult_mortality,
      Alcohol = input$alcohol,
      BMI = input$bmi,
      GDP = input$gdp,
      Schooling = input$schooling
    )
    predicted <- predict(model, new_data)
    paste("Predicted Life Expectancy:", round(predicted, 2))
  })
  
  #plot
  output$regressionPlot <- renderPlot({
    ggplot(regression_data, aes(x = Life.expectancy, y = Predicted_Life_Expectancy)) +
      geom_point() +
      geom_abline(color = "red") +
      labs(title = "Actual vs Predicted Life Expectancy", x = "Actual", y = "Predicted")
  })
}

shinyApp(ui = ui, server = server)
```
```{r}
install.packages('rsconnect')
```
```{r}
rsconnect::setAccountInfo(name='ctlangevin',
			  token='A5A7176AF2B3D83CD9ED27EFF66D6791',
			  secret='90/ly7a4PR80oFVEMkHTuzUkJIJiXdvV946Pquaa')
```

```{r}
library(rsconnect)
```


```{r}
library(rsconnect)
    rsconnect::deployApp('C:/Users/chris/ShinyApp/DS501_HW4.Rmd')
```

